version: 2
updates:
  - package-ecosystem: uv
    open-pull-requests-limit: 0
    directory: /
    schedule:
      interval: weekly
    groups:
      documentation-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    open-pull-requests-limit: 0
    directory: /
    schedule:
      interval: weekly
    groups:
      workflow-actions:
        patterns: ["*"]
