from __future__ import annotations

import tomllib

import pytest

from scripts.export_ecosystem import SOURCE, render


def load() -> dict:
    return tomllib.loads(SOURCE.read_text(encoding="utf-8"))


def test_manifest_renders_every_public_family_project() -> None:
    output = render(load())
    expected = {
        "create-hayate",
        "golden-app",
        "hayate",
        "hayate-admin",
        "hayate-auth",
        "hayate-fetch",
        "hayate-htmx",
        "hayate-mcp",
        "hayate-openapi",
        "hayate-sql",
    }
    for name in expected:
        assert f"## {name}\n" in output
    assert output.count("## ") == len(expected)
    assert "Generated by scripts/export_ecosystem.py" in output
    assert "Every package is pre-1.0" in output


def test_duplicate_package_is_rejected() -> None:
    data = load()
    data["packages"].append(dict(data["packages"][0]))
    with pytest.raises(ValueError, match="duplicate package"):
        render(data)


def test_mutable_source_reference_is_rejected() -> None:
    data = load()
    data["packages"][0]["source_commit"] = "main"
    with pytest.raises(ValueError, match="not immutable"):
        render(data)
