"""Generate the public family map from a dated ecosystem manifest."""

from __future__ import annotations

import argparse
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "ecosystem.toml"
OUTPUT = ROOT / "docs" / "ecosystem" / "index.md"


def render(data: dict) -> str:
    if data.get("schema_version") != 1:
        raise ValueError("unsupported ecosystem manifest schema")
    packages = data.get("packages")
    if not isinstance(packages, list) or not packages:
        raise ValueError("ecosystem manifest needs packages")

    names: set[str] = set()
    rows = []
    details = []
    for package in packages:
        name = package["name"]
        if name in names:
            raise ValueError(f"duplicate package {name!r}")
        names.add(name)
        version = package["version"]
        repository = package["repository"]
        status = package["status"]
        role = package["role"]
        use_when = package["use_when"]
        source_commit = package["source_commit"]
        if len(source_commit) != 40:
            raise ValueError(f"{name!r} source commit is not immutable")
        release = f"[`{version}`]({package['pypi']})" if package.get("pypi") else f"`{version}`"
        rows.append(f"| [`{name}`]({repository}) | {release} | {role} | {status} |")
        details.append(
            "\n".join(
                (
                    f"## {name}",
                    "",
                    use_when,
                    "",
                    f"**Current evidence:** {status}, version `{version}` · "
                    f"[source at `{source_commit[:12]}`]"
                    f"({repository}/tree/{source_commit})",
                    "",
                    f"[Repository]({repository})"
                    + (f" · [PyPI]({package['pypi']})" if package.get("pypi") else ""),
                )
            )
        )

    return (
        "<!-- Generated by scripts/export_ecosystem.py; edit data/ecosystem.toml. -->\n\n"
        "# Hayate family\n\n"
        "Choose packages by the boundary your application needs. The core stays small; "
        "capabilities are explicit packages with their own release and evidence.\n\n"
        f"This snapshot is dated **{data['as_of']}** and is pinned to "
        f"[`{data['source_repository']}` at `{data['source_commit'][:12]}`]"
        f"(https://github.com/{data['source_repository']}/tree/{data['source_commit']}). "
        "Every package is pre-1.0; check the compatibility snapshot before combining "
        "versions.\n\n"
        "| Project | Version | Responsibility | Release state |\n"
        "|---|---:|---|---|\n" + "\n".join(rows) + "\n\n"
        f"[Open the tested compatibility snapshot]({data['compatibility_url']})"
        "\n\n" + "\n\n".join(details) + "\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    expected = render(data)
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit("docs/ecosystem/index.md is stale; run scripts/export_ecosystem.py")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
